name: Build Laravel Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, bcmath, xml, ctype, json, curl

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run tests (optional)
        run: php artisan test

      - name: Zip vendor folder
        run: zip -r vendor.zip vendor

      - name: Upload vendor.zip artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: vendor-folder
          path: vendor.zip
